### ISSUE TITLE
overflow error

### ISSUE THREAD

**Issue by jmintveld** [jellespijker/pyDewesoft#1]
having processed dxd files before I know this module works great, however since I reinstalled my code the pyDewesoft module doesn't work. So I suspect an installation mistake/problem but can't identify it.

I get the following error if I want to load a dxd file:

> Connected to pydev debugger (build 193.5662.61)
> Traceback (most recent call last):
>   File "C:\Program Files\JetBrains\PyCharm 2019.3.1\plugins\python\helpers\pydev\pydevd.py", line 1434, in _exec
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "C:\Program Files\JetBrains\PyCharm 2019.3.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
>   File "C:/GIT/pyDewesoft/runtest.py", line 7, in <module>
>     dxd_output.read(filename=file_path, ch_select=None)
>   File "C:\GIT\pyDewesoft\pyDewesoft\DataReader.py", line 319, in read
>     finfo = self._open_file(filename)
>   File "C:\GIT\pyDewesoft\pyDewesoft\DataReader.py", line 371, in _open_file
>     if self._lib.DWOpenDataFile(fname, addressof(finfo)) != DWStatus.DWSTAT_OK.value:
> ctypes.ArgumentError: argument 2: <class 'OverflowError'>: int too long to convert
> 
> Process finished with exit code 1

i use python 3.6,  64 bit.
Are there any suggestion?

**Comment by jellespijker** [comment]
Could you share a measurement file, which exhibits this problem? Then I can try to replicate this issue

**Comment by jmintveld** [comment]
[example.zip](https://github.com/jellespijker/pyDewesoft/files/4076525/example.zip)

**Comment by jellespijker** [comment]
The bug can be reproduced on an other windows 10 machine running python 3.6

**Comment by jellespijker** [comment]
The value returned by `addressof(finfo)` is to big to cast in to a C type integer.
But it seems to be unnecessary since python objects are passed as pointers as is.

```py
fname = c_char_p(filename.encode())
finfo = DWFileInfo(0, 0, 0)
if self._lib.DWOpenDataFile(fname, addressof(finfo)) != DWStatus.DWSTAT_OK.value:
    raise RuntimeError('Could not open file: ' + filename)
```

change it to
```py
fname = c_char_p(filename.encode())
finfo = DWFileInfo(0, 0, 0)
if self._lib.DWOpenDataFile(fname, finfo) != DWStatus.DWSTAT_OK.value:
    raise RuntimeError('Could not open file: ' + filename)
```
seems to work

**Comment by jmintveld** [comment]
that works!!
thank you
